language: android
jdk:
- oraclejdk8
env:
  global:
  - ANDROID_API=28
  - OWNER=${TRAVIS_REPO_SLUG%/*}
  - DEV=${OWNER/vanhiep184/dev}
  - BRANCH=${TRAVIS_BRANCH/main/}
  - TAG=${DEV}${BRANCH:+_}${BRANCH}
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-${ANDROID_API}
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
before_install:
- openssl aes-256-cbc -K $encrypted_59da33dcd24e_key -iv $encrypted_59da33dcd24e_iv
  -in keyhrm.enc -out keyhrm -d
- yes | sdkmanager "platform-tools" "platforms;android-28"
- chmod +x gradlew
script:
- "./gradlew clean build connectedAndroidTest -PdisablePreDex --stacktrace"
notifications:
  email: true
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- export APP_VERSION=$(./gradlew :app:printVersionName)
deploy:
  provider: releases
  user: "$GITHUB_USERNAME"
  password:
    secure: o0jffA6rZO6LR965MVbqdTI62WCzvliy9rOlZokSeYGs0VHl3HHaIh223BoFHMOnMXhLva2y3KDldq3bGiv1p8YeG1yyw3AaFOdVabDxvOepx2QpJ2IcegdTh3mS02Qo36rgjaiVNkwtyzbL6LN/bvSMDOBSoE7slRCOO22w0CRz5UHuZDRJxKt8X0Mk56nyXF+uyrC9YkAvWlMEhsZAN+0rnnMJ86aRjcb1Rl14nJUP9bSC75HxOEhfqGgvEIJ2tX9C+f8t/m9P8iyAvbejpM4yDmJfsHmsLbGdnPfQojYpaFbxkfkTjRNGLsEOSlUErWGbiBtRu88KSxKQD31fOWhNKuFlaPqiTbf6jdG3opscwTizC0jGRxTTuMXDfKYzZdu9iZSooCto+n0pNGQxuuo/Lq5hBac9ycTEYX5E0cDOOLvu/aV2AEM/4U/oTRhJsabfBjPUsHjPNIq6ECu17B4PXNQDxgnfc6uQCPDAofpqIop/Vs/kKUrR5vFFqx6N5K6BD4wv+Uek3gr76mZcm0KVJ2vRt/h8XktMTP9ug3mUXVCRtOQ2BiqmkHWyE3c94miLTqKMj+HA7Wr1EvJccU7z3coxdoZTpwKvcGY15EI5mP2xon42KNw+MKOg81XkQyEWYxgQZfL1FjgQrQIiSZkPQCwFAX3vE140lqDSWuM=
  file: app/build/outputs/apk/release/*
  file_glob: true
  skip_cleanup: true
  overwrite: true
  name: "$APP_VERSION"
  tag_name: "$APP_VERSION"
  on:
    tags: true
    branch: main
# after_success:
# - sh set_tags.sh
