language: android
jdk:
- oraclejdk8
env:
  global:
  - ANDROID_API=28
  - OWNER=${TRAVIS_REPO_SLUG%/*}
  - DEV=${OWNER/vanhiep184/dev}
  - BRANCH=${TRAVIS_BRANCH/main/}
  - TAG=${DEV}${BRANCH:+_}${BRANCH}
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-${ANDROID_API}
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
before_install:
- openssl aes-256-cbc -K $encrypted_59da33dcd24e_key -iv $encrypted_59da33dcd24e_iv
  -in keyhrm.enc -out keyhrm -d
- yes | sdkmanager "platform-tools" "platforms;android-28"
- chmod +x gradlew
# - tar -cvf secrets.tar keyhrm service.json
# - tar -xvf secrets.tar
script:
# - "./gradlew assembleRelease"
# - "./gradlew clean build"
# - if [ "$TRAVIS_BRANCH" = "main" ]; then ./gradlew publish; else ./gradlew build;
#   fi
- "./gradlew clean build connectedAndroidTest -PdisablePreDex --stacktrace"
notifications:
  email: true

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- export APP_VERSION=$(./gradlew :app:printVersionName)
# - export APP_CHANGELOG=$(cat app/src/main/play/release-notes/en-US/default.txt)
- git tag -f travis-${TAG}-build-${APP_VERSION}
- git remote add gh
    https://${OWNER}:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
- git push gh :travis-${TAG}-build-${APP_VERSION} || true
- git push -f gh travis-${TAG}-build-${APP_VERSION}
- git remote remove gh
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: app/build/outputs/apk/release/*
  file_glob: true
  skip_cleanup: true
  overwrite: true
  name: "$APP_VERSION"
  tag_name: "$APP_VERSION"
  on:
    tags: true
    branch: main
# after_success:
# - sh set_tags.sh

notifications:  
  email:
    recipients:
      - levanhiep.95.95@gmail.com
    on_success: always  
    on_failure: always