language: android
jdk:
- oraclejdk8
env:
  global:
  - ANDROID_API=28
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-${ANDROID_API}
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
before_install:
- openssl aes-256-cbc -K $encrypted_59da33dcd24e_key -iv $encrypted_59da33dcd24e_iv
  -in keyhrm.enc -out keyhrm -d
- yes | sdkmanager "platform-tools" "platforms;android-28"
- tar -cvf secrets.tar keyhrm service.json
- tar -xvf secrets.tar
script:
- "./gradlew assembleRelease"
- "./gradlew build"
# - if [ "$TRAVIS_BRANCH" = "main" ]; then ./gradlew publish; else ./gradlew build;
#   fi
before_deploy:
- export APP_VERSION=$(./gradlew :app:printVersionName)
- export APP_CHANGELOG=$(cat app/src/main/play/release-notes/en-US/default.txt)
deploy:
  api_key: "$GITHUB_TOKEN"
  file: app/build/outputs/apk/release/*
  file_glob: true
  skip_cleanup: true
  overwrite: true
  name: "$APP_VERSION"
  tag_name: "$APP_VERSION"
  on:
    branch: main
